[package]
name = "fractal"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
winit = "*"
num-complex = "*"
rayon = "*"
bytemuck = { version = "*", features = ["derive"] }
wgpu = "*"
pollster = "*"
tokio = { version = "*", features = ["full"] }
anyhow = "*"
num_cpus = "*"
image = "*"


[profile.release]
opt-level = 3         # Apply the highest level of optimizations.
lto = true            # Enable Link Time Optimization
codegen-units = 1     # Reduce parallel code generation which can improve optimizations
panic = 'abort'       # Abort on panic. Can have minor performance benefits over unwinding.
debug = true          # Add debug symbols for profiling.
